apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
spec:
  rules:
    - host: inventory.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service # Make sure this matches your frontend service name!
                port:
                  number: 80